build-server-linux:

g++ ./src/serenity_linux_server.cpp -o serenity-server

build-server-windows:


build-client-linux:

build-client-windows:

g++ ./src/serenity_windows_client.cpp -o serenity.exe

clean:


run-client-windows:

./serenity.exe 192.168.1.175

run-client-linux:

run-server-linux:

./serenity-server

run-server-windows: